import { Page, Text, View } from '@react-pdf/renderer';

import { type TaskDetail } from '../types';
import { PDFImage } from './PDFImage';
import { pdfStyles } from './styles';

interface PDFTitlePageProps {
  task: TaskDetail;
}

/**
 * PDF标题页组件
 * KISS: 简单的标题页布局
 */
export function PDFTitlePage({ task }: PDFTitlePageProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('ja-JP', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  return (
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.titlePage}>
        <Text style={pdfStyles.title}>タスクレポート</Text>

        <View style={pdfStyles.marginBottom}>
          <Text style={pdfStyles.subtitle}>
            {task.tid} - {task.name}
          </Text>
        </View>

        <View style={{ marginBottom: 30 }}>
          {task.description && (
            <Text style={{ fontSize: 12, textAlign: 'center', color: '#666666', lineHeight: 1.5 }}>
              {task.description}
            </Text>
          )}
        </View>

        {/* Task thumbnail image */}
        {task.s3_path && (
          <View style={{ marginBottom: 20, alignItems: 'center' }}>
            <PDFImage src={task.s3_path} caption="タスクサムネイル" maxWidth={300} maxHeight={200} />
          </View>
        )}

        <View style={{ marginBottom: 20 }}>
          <Text style={{ fontSize: 10, color: '#666666', textAlign: 'center' }}>
            作成日: {formatDate(task.created_at)}
          </Text>
          <Text style={{ fontSize: 10, color: '#666666', textAlign: 'center' }}>
            更新日: {formatDate(task.updated_at)}
          </Text>
        </View>

        <View style={{ marginTop: 40 }}>
          <Text style={{ fontSize: 8, color: '#999999', textAlign: 'center' }}>
            Generated by AI Mage Supervision System
          </Text>
          <Text style={{ fontSize: 8, color: '#999999', textAlign: 'center' }}>
            {new Date().toLocaleDateString('ja-JP')}
          </Text>
        </View>
      </View>
    </Page>
  );
}
